apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: ebs-dynamic-pvc
 namespace: roboshop
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 5Gi
 storageClassName: ebs